language:
- objective-c
env:
  global:
    - QT_URL=http://download.qt.io/archive/qt/4.8/4.8.6/qt-opensource-mac-4.8.6-1.dmg
    - BUILD_COMMIT='latest-tag'  # comment out to build version in submodule
    - REPO_DIR=pyside-setup
  matrix:
  - VERSION=2.7.10
  - VERSION=3.3.5
  - VERSION=3.4.2
install:
  - export MACOSX_DEPLOYMENT_TARGET=10.6  # Snow Leopard
  - source run_install.sh
  - get_python_environment macpython $VERSION venv
  - pip install delocate
  - pip install sphinx==1.1.3  # sphinx.ext.refcounting needed
  - if [ -n "$BUILD_COMMIT" ]; then
        checkout_commit $REPO_DIR $BUILD_COMMIT;
    fi
  - cd $REPO_DIR
  - git submodule update --init
  - export CPATH=$CPATH:/usr/local/include
  - python setup.py bdist_wheel
  - delocate-listdeps dist/*.whl # lists library dependencies
  - delocate-wheel dist/*.whl # copies library dependencies into wheel
  - delocate-addplat --rm-orig -x 10_9 -x 10_10 dist/*.whl
  - pip install dist/*.whl
  - cd ..
script:
  - python -c 'import PySide'
before_deploy: cd $REPO_DIR/dist
deploy:
  provider: cloudfiles
  username: travis-worker
  api_key:
    secure: K9JEFezfB40JDYntdoBKfxFD6qAlWGo1WaNM269JUAS6+8taD8gLOe83r1hyZWa0m2hdTilk0ySDUxjs+aTe2f4+ES+s8aiORSTFHChMUL/7+vteaHUle3BEuUDx23mnx5XNQT/n1gX2WkWwqZMH7JDAsHbexuquQZfJVAWRpo4=
  region: ORD
  container: wheels
  skip_cleanup: true
